
INSERT INTO Currency(CCY_CODE) VALUES ('AUD');
INSERT INTO Currency(CCY_CODE) VALUES ('CAD'); 
INSERT INTO Currency(CCY_CODE) VALUES ('CNY');
INSERT INTO Currency(CCY_CODE) VALUES ('CZK');
INSERT INTO Currency(CCY_CODE) VALUES ('DKK');
INSERT INTO Currency(CCY_CODE) VALUES ('EUR');
INSERT INTO Currency(CCY_CODE) VALUES ('GBP');
INSERT INTO Currency(CCY_CODE) VALUES ('JPY');
INSERT INTO Currency(CCY_CODE) VALUES ('NOK');
INSERT INTO Currency(CCY_CODE) VALUES ('NZD');
INSERT INTO Currency(CCY_CODE) VALUES ('USD');


INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('AUDUSD', 0.8371);
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('CADUSD', 0.8711); 
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('USDCNY', 6.1715);
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('EURUSD', 1.2315); 
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('GBPUSD', 1.5683);
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('NZDUSD', 0.7750); 
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('USDJPY', 119.95);
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('EURCZK', 27.6028); 
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('EURDKK', 7.4405);
INSERT INTO RATE_MAP (CCY1CCY2, RATE) VALUES ('EURNOK', 8.6651);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','CAD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','CNY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','CZK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','DKK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','EUR');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','GBP');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','USD','NZD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('AUD','D','USD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','CNY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','CZK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','DKK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','EUR');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','GBP');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','USD','NZD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CAD','D','USD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CNY','USD','CZK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CNY','USD','DKK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CNY','USD','EUR');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CNY','USD','GBP');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CNY','USD','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CNY','USD','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CNY','USD','NZD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CZK','EUR','DKK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CZK','USD','GBP');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CZK','USD','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CZK','EUR','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CZK','USD','NZD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('CZK','EUR','USD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('DKK','USD','GBP');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('DKK','USD','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('DKK','EUR','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('DKK','USD','NZD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('DKK','EUR','USD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('EUR','D','CZK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('EUR','D','DKK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('EUR','USD','GBP');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('EUR','USD','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('EUR','D','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('EUR','USD','NZD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('EUR','D','USD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('GBP','USD','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('GBP','USD','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('GBP','USD','NZD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('GBP','D','USD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('JPY','USD','NOK');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('JPY','USD','NZD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('NOK','USD','NZD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('NOK','EUR','USD');

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('NZD','D','USD');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('USD','D','JPY');
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES ('USD','D','CNY');

/*
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',2);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',3);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',4);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',5);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',6);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',7);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',8);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (1,'D',11);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',3);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',4);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',5);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',6);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',7);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',8);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (2,'D',11);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'USD',4);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'USD',5);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'USD',6);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'USD',7);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'USD',8);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'USD',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (3,'D',11);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (4,'EUR',5);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (4,'USD',7);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (4,'USD',8);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (4,'EUR',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (4,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (4,'EUR',11);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (5,'USD',7);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (5,'USD',8);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (5,'EUR',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (5,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (5,'EUR',11);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (6,'D',4);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (6,'D',5);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (6,'USD',7);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (6,'USD',8);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (6,'D',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (6,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (6,'D',11);


INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (7,'USD',8);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (7,'USD',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (7,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (7,'D',11);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (8,'USD',9);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (8,'USD',10);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (9,'USD',10);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (9,'EUR',11);

INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (10,'D',11);
INSERT INTO CURRENCY_MATRIX (BASE_ID,MAPPING_VALUE,TERM_ID) VALUES (11,'D',8);
*/





